//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnigmeQuizz_TAHRI_CHELIAN
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnigmeQuizz_TAHRI_CHELIAN_BDDEntities : DbContext
    {
        public EnigmeQuizz_TAHRI_CHELIAN_BDDEntities()
            : base("name=EnigmeQuizz_TAHRI_CHELIAN_BDDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Enigme> Enigme { get; set; }
        public virtual DbSet<Joueur> Joueur { get; set; }
        public virtual DbSet<QuestionQuizz> QuestionQuizz { get; set; }
        public virtual DbSet<Quizz> Quizz { get; set; }
        public virtual DbSet<ReponseQuizz> ReponseQuizz { get; set; }
    }
}
