//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnigmeQuizz_TAHRI_CHELIAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enigme
    {
        public int Id_enigme { get; set; }
        public string enigme1 { get; set; }
        public string reponseEnigme { get; set; }
    }
}
