//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnigmeQuizz_TAHRI_CHELIAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quizz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quizz()
        {
            this.QuestionQuizz1 = new HashSet<QuestionQuizz>();
        }
    
        public int Id_quizz { get; set; }
        public Nullable<int> scoreQuizz { get; set; }
        public string theme { get; set; }
    
        public virtual QuestionQuizz QuestionQuizz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionQuizz> QuestionQuizz1 { get; set; }
    }
}
