//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnigmeQuizz_TAHRI_CHELIAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReponseQuizz
    {
        public int Id_reponseQuizz { get; set; }
        public string reponseQuizz1 { get; set; }
        public string isTrue { get; set; }
        public int Questions_Quizz { get; set; }
    
        public virtual QuestionQuizz QuestionQuizz1 { get; set; }
    }
}
